default: &default
  adapter: mysql2
  database: mydb
  host: localhost
  username: root
  password: "root"

development:
  <<: *default
  database: db/my_event

test:
  <<: *default
  database: db/test_my_event

production:
  <<: *default
  database: db/production_my_event